### ISSUE TITLE
RSS as "raw XML"

### ISSUE THREAD

**Issue by scl-4711** [jariolaine/apex-blog#11]
Hi Jari, 
I tried to register my blog for the [APEX Developer Blogs](https://apps.cloudnueva.com/ords/r/apps/apex_blogs/home?session=517499219535704) from Jon Dixon.

He needs "raw XML" like the following: hartenfeller.dev/orclapex-rss.xml

Is it possible that you implement this in the blog? Maybe as alternative XML ?

Kind regards
Steffen

**Comment by jariolaine** [comment]
Thanks. I will check this.

**Comment by jariolaine** [comment]
Do you have more information how RSS should be changed? If you open your blog RSS in Chrome browser, and then press CTRL+U you can see raw XML. By default RSS feed displays like HTML page in browser because [XSL style sheet](https://www.w3.org/Style/XSL/WhatIsXSL.html) included. Is that the problem?

**Comment by jariolaine** [comment]
You can also try online RSS validators for your blog RSS
[https://validator.w3.org/feed/](https://validator.w3.org/feed/)
[https://www.rssboard.org/rss-validator/](https://www.rssboard.org/rss-validator/)

**Comment by scl-4711** [comment]
No, Jon wrote he needs the raw mxl for adding the blog.
Can you provide the URL without the XSL style sheet too?

**Comment by jariolaine** [comment]
Could you please ask him to explain what is wrong or tell exact error when there is XSL style sheet?

**Comment by jariolaine** [comment]
I will add RSS without XSL if that is the problem. But I think that isn't, because at least online RSS feed validators don't complain about that and RSS readers can read the feed without problem. I can also query generated RSS in database without any problem.
If Jonathan could join this discussion and explain more details it would be very helpful.

**Comment by scl-4711** [comment]
I wrote him per email and asked him to join here at git.

**Comment by jon-dixon** [comment]
Hi. My code can see the posts, the issue is that the RSS does not contain the content of the Post i.e. the "description" tag. using https://hartenfeller.dev/orclapex-rss.xml as an example, it includes the post content in the description field, whereas https://asc.web-republic.de/ords/r/sc/blog/pgm?request=application_process%3Drss.xml does not.
<img width="1184" alt="image" src="https://github.com/jariolaine/apex-blog/assets/107701070/14f22f85-ad17-4392-a5f2-4636060d6cec">

**Comment by jariolaine** [comment]
Thank you very much @jon-dixon .

I have made change. Could you please check my blog rss
[https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Drss.xml](https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Drss.xml)?

There is element content:encoded like RSS found in [https://fuzziebrain.com/content/rss.xml](https://fuzziebrain.com/content/rss.xml).
I'm also working on atom feed like XML, if that's more suitable.

**Comment by jon-dixon** [comment]
Hi Jari,

I see a description tag, but it does not contain the entire content of the post. My code filters out blog posts that are less than 100 characters in length. If it is possible to include the entire post content then it should pull it in.

***@***.***

--
Kind Regards,
Jon Dixon
c: 330.310.0591
e: ***@***.******@***.***>
[signature_391406061]



From: Jari Laine ***@***.***>
Date: Monday, November 13, 2023 at 6:20 PM
To: jariolaine/apex-blog ***@***.***>
Cc: Jonathan Dixon ***@***.***>, Mention ***@***.***>
Subject: Re: [jariolaine/apex-blog] RSS as "raw XML" (Issue #11)

Thank you very much @jon-dixon<https://github.com/jon-dixon> .

I have made change. Could you please check my blog rss
https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Drss.xml?

There is element content:encoded like RSS found in https://fuzziebrain.com/content/rss.xml.
I'm also working on atom feed like XML, if that's more suitable.

**Comment by jariolaine** [comment]
Thank you very much. I will do needed change.

**Comment by jariolaine** [comment]
@jon-dixon, could you please add my blog using this feed [https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Datom.xml](https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Datom.xml)

If it's ok I will publish release.

Thanks advance.

**Comment by jon-dixon** [comment]
Hi Jari,

That worked great; your last 25 posts have now been indexed. I used the URL from your Twitter Profile as your Profile Picture:
https://pbs.twimg.com/profile_images/1650774737/picture_400x400.jpg

***@***.***

--
Kind Regards,
Jon Dixon
c: 330.310.0591
e: ***@***.******@***.***>
[signature_3634270884]



From: Jari Laine ***@***.***>
Date: Friday, November 17, 2023 at 10:22 PM
To: jariolaine/apex-blog ***@***.***>
Cc: Jonathan Dixon ***@***.***>, Mention ***@***.***>
Subject: Re: [jariolaine/apex-blog] RSS as "raw XML" (Issue #11)

@jon-dixon<https://github.com/jon-dixon>, could you please add my blog using this feed https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Datom.xml

If it's ok I will publish release.

Thanks advance.

**Comment by jariolaine** [comment]
Thank you very much @jon-dixon. And thank you @scl-4711 for raising this enhancement idea.

**Comment by jon-dixon** [comment]
Hi Jari,

Should I use this URL now for Steffen’s Blog?
https://asc.web-republic.de/ords/r/sc/blog/pgm?request=application_process%3Datom.xml
When I try it, I get no content back.
***@***.***


When I try your blog’s URL
https://cloud.jaris.fi/ords/r/jaris/blog/pgm?request=application_process%3Datom.xml

I get the following:
***@***.***


--
Kind Regards,
Jon Dixon
c: 330.310.0591
e: ***@***.******@***.***>
[signature_987763448]



From: Jari Laine ***@***.***>
Date: Saturday, November 18, 2023 at 10:12 PM
To: jariolaine/apex-blog ***@***.***>
Cc: Jonathan Dixon ***@***.***>, Mention ***@***.***>
Subject: Re: [jariolaine/apex-blog] RSS as "raw XML" (Issue #11)

Thank you very much @jon-dixon<https://github.com/jon-dixon>. And thank you @scl-4711<https://github.com/scl-4711> for raising this enhancement idea.

**Comment by jariolaine** [comment]
Hi Jon,
I think Steffen hasn't yet upgrade his blog. This is why atom feed URL isn't yet available on his blog.

**Comment by scl-4711** [comment]
Hi together - yes, that's true, I have to upgrade first. Maybe tomorrow 😉

**Comment by jon-dixon** [comment]
No worries, just wanted to make sure I hadn’t missed something.

On Nov 19, 2023, at 8:17 AM, Steffen Clauß ***@***.***> wrote:

﻿

Hi together - yes, that's true, I have to upgrade first. Maybe tomorrow 😉

**Comment by scl-4711** [comment]
Ok, now I have updated my blog too...

**Comment by jon-dixon** [comment]
Excellent, I activated your blog, and your posts have some through.

***@***.***

--
Kind Regards,
Jon Dixon
c: 330.310.0591
e: ***@***.******@***.***>
[signature_2839503833]



From: Steffen Clauß ***@***.***>
Date: Monday, November 20, 2023 at 3:14 AM
To: jariolaine/apex-blog ***@***.***>
Cc: Jonathan Dixon ***@***.***>, Mention ***@***.***>
Subject: Re: [jariolaine/apex-blog] RSS as "raw XML" (Issue #11)

Ok, now I have updated my blog too...
