### ISSUE TITLE
BLog login ERROR

### ISSUE THREAD

**Issue by pengzz9527** [jariolaine/apex-blog#13]
ORA-04063: package body "WKSP_AIGOOGLE.BLOG_UTIL" has errors
Technical Info (only available for developers)
is_internal_error: false
ora_sqlcode: -4063
ora_sqlerrm: ORA-04063: package body "WKSP_AIGOOGLE.BLOG_UTIL" has errors
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS_NATIVE", line 55
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 126
ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2647
ORA-06508: PL/SQL: could not find program unit being called: "WKSP_AIGOOGLE.BLOG_UTIL"
ORA-06512: at line 1
ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_230200", line 810
ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2607
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 97
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 430
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC", line 614
ORA-06512: at "APEX_230200.WWV_FLOW_EXEC_LOCAL", line 3062
ORA-06512: at "APEX_230200.WWV_FLOW_EXEC", line 2823
ORA-06512: at "APEX_230200.WWV_FLOW_EXEC", line 2861
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS_NATIVE", line 34
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS_NATIVE", line 1347
ORA-06512: at "APEX_230200.WWV_FLOW_PLUGIN", line 3634
component.type: APEX_APPLICATION_PROCESSES
component.id: 53582057650954562157
component.name: Initialize Items
error_backtrace:
ORA-06512: at line 1
ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_230200", line 810
ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2607
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS_NATIVE", line 55
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 126
ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2647
ORA-06512: at line 1
ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_230200", line 810
ORA-06512: at "APEX_230200.WWV_FLOW_DYNAMIC_EXEC", line 2607
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 97
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC_PLSQL", line 430
ORA-06512: at "APEX_230200.WWV_FLOW_CODE_EXEC", line 614
ORA-06512: at "APEX_230200.WWV_FLOW_EXEC_LOCAL", line 3062
ORA-06512: at "APEX_230200.WWV_FLOW_EXEC", line 2823
ORA-06512: at "APEX_230200.WWV_FLOW_EXEC", line 2861
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS_NATIVE", line 34
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS_NATIVE", line 1347
ORA-06512: at "APEX_230200.WWV_FLOW_PLUGIN", line 3634
ORA-06512: at "APEX_230200.WWV_FLOW_PROCESS", line 192
error_statement:
begin blog_util.initialize_items(
  p_app_id => :APP_ID
);
end;

**Comment by jariolaine** [comment]
Hi,

What is your database version?
What is database MAX_STRING_SIZE parameter value?

```
select name, value
from v$parameter
where name = 'max_string_size';
```

Please run below and post output:
```
alter view blog_v_posts compile;
alter package blog_util compile;
select *
from user_errors;
```

**Comment by pengzz9527** [comment]
BLOG_UTIL PACKAGE BODY 1 236 21 PLS-00201: identifier
'BLOG_V_POSTS.PUBLISHED_ON' must be declared ERROR 201
BLOG_UTIL PACKAGE BODY 2 0 0 PL/SQL: Compilation unit analysis terminated
ERROR 0
BLOG_V_ARCHIVE_YEAR VIEW 1 0 0 ORA-00942: 表或视图不存在 ERROR 0
BLOG_V_CATEGORIES VIEW 1 0 0 ORA-00942: 表或视图不存在 ERROR 0
BLOG_V_COMMENTS VIEW 1 0 0 ORA-00942: 表或视图不存在 ERROR 0
BLOG_V_POSTS_LAST20 VIEW 1 0 0 ORA-00942: 表或视图不存在 ERROR 0
BLOG_V_TAGS VIEW 1 0 0 ORA-00942: 表或视图不存在 ERROR

-------------------------------------------------------------------------------------------------
The trird line means : ORA-00942: table or view does not exist





Jari Laine ***@***.***> 于2024年1月23日周二 14:33写道：

**Comment by pengzz9527** [comment]
Hi,

What is your database version?
--------------------------------------------
Oracle Database 19c EE Extreme Perf Release 19.0.0.0.0 - Production

 deployed on apex.oracle.com  ；

What is database MAX_STRING_SIZE parameter value?



select name, value
from v$parameter
where name = 'max_string_size';
--------------------------------------------------
It should be no access permission，get error: 	Error at line 2/6: ORA-00942: table or view does not exist   ,when excute :
select name, value
from v$parameter
where name = 'max_string_size';

**Comment by jariolaine** [comment]
There is issue in view BLOG_V_POSTS when database parameter MAX_STRING_SIZE value is STANDARD.

Create view using attached DDL 
[blog_v_posts_fix_issue_13.zip](https://github.com/jariolaine/apex-blog/files/14039442/blog_v_posts_fix_issue_13.zip)

And compile invalid objects.
```
alter view blog_v_posts_last20 compile;
alter view blog_v_archive_year compile;
alter view blog_v_comments compile;
alter view blog_v_categories compile;
alter view blog_v_archive_year compile;
alter view blog_v_tags compile;
alter package blog_util compile;
alter package blog_xml compile;
```

Run below insert where you replace < admin application id here > part with actual application id

```
insert into blog_settings(display_seq,is_nullable,attribute_name,data_type,attribute_group_message,int_min,int_max,attribute_value) values('30','0','G_ADMIN_APP_ID','STRING','INTERNAL',null,null, <admin application id here>);
```

Drop view
```
drop view blog_v_version;
```

Install blog public application again.

**Comment by pengzz9527** [comment]
Trank you ,Problem solved, perfect!

**Comment by jariolaine** [comment]
Waiting that bug #12 is fixed from Oracle to continue development.
