### ISSUE TITLE
Error with new constant handling and translated app

### ISSUE THREAD

**Issue by scl-4711** [jariolaine/apex-blog#14]
Hi Jari,

none of the new "constants" work if I translate the latest app to german and use it as Application Primary Language.
As usual I duplicated and translated all text messages to german.

Where do you init the items?

Best regards
Steffen

**Comment by jariolaine** [comment]
Hi Steffen,
There is application process Initialize session that sets items values.
I did test that translation should work and can't reproduce issue.
Could you please explain in details steps how reproduce issue?
Regards,
Jari

**Comment by jariolaine** [comment]
Please note that global page items storage is set Per User (Persistent). Those items values don't show if you check builder toolbar View Session State. Values are preferences, so you need navigate to Administration -> Manage Service -> Session State and see report Preferences by User. Application name and description are text messages.

**Comment by jariolaine** [comment]
One problem might be that global page region Application Banner is cached. In admin application change e.g. blog name. It should clear cache. Then change name back.

**Comment by scl-4711** [comment]
![image](https://github.com/jariolaine/apex-blog/assets/12970066/9dc74e29-2b80-434b-b751-e3d157daf6dc)
![image](https://github.com/jariolaine/apex-blog/assets/12970066/d9d0e8e0-d52a-4fc1-9133-8c902278661f)

The APP_TEXT$BLOG_APP_NAME is missing top left, and "BLOG_POWERED_BY".

Everything else seems to be ok :-)

**Comment by scl-4711** [comment]
> Hi Steffen, There is application process Initialize session that sets items values. I did test that translation should work and can't reproduce issue. Could you please explain in details steps how reproduce issue? Regards, Jari

Do the translation steps in "Shared components -> Globalization -> Application Translations" and switch the Application Primary Language afterwards to new language. That's all.

**Comment by jariolaine** [comment]
I have removed shortcut "BLOG_POWERED_BY" long time ago. Where that come from? I did check application export and there is &APP_TEXT$BLOG_APP_NAME. and text message BLOG_APP_NAME.

**Comment by jariolaine** [comment]
> Do the translation steps in "Shared components -> Globalization -> Application Translations" and switch the Application Primary Language afterwards to new language. That's all.

Where you get all translations for text messages?

**Comment by scl-4711** [comment]
> One problem might be that global page region Application Banner is cached. In admin application change e.g. blog name. It should clear cache. Then change name back.

> Owner

If I change 
![image](https://github.com/jariolaine/apex-blog/assets/12970066/7e1efbc1-be1d-4b83-9191-d7c89a116c5d)
to
![image](https://github.com/jariolaine/apex-blog/assets/12970066/75b5016f-a69d-4e65-979e-2d50195e9d50)
it works

I find no items with name "APP_ID" and "DEBUG" in the whole app ?!

**Comment by scl-4711** [comment]
> > Do the translation steps in "Shared components -> Globalization -> Application Translations" and switch the Application Primary Language afterwards to new language. That's all.
> 
> Where you get all translations for text messages?

I translated the texts at some point - and saved them in a table so that I don't have to do that again and again ;-)

**Comment by jariolaine** [comment]
> I find no items with name "APP_ID" and "DEBUG" in the whole app ?!

Those are APEX internal items.

**Comment by scl-4711** [comment]
> BLOG_POWERED_BY

![image](https://github.com/jariolaine/apex-blog/assets/12970066/ee2f2137-b7da-4f89-bdbd-80118a590440)

My failure...

**Comment by jariolaine** [comment]
> I translated the texts at some point - and saved them in a table so that I don't have to do that again and again ;-)

Ok, that's good. And how about other text that need to be translated? If you use same XLF file that can be downloaded from your blog, it might not work as expected.

**Comment by scl-4711** [comment]
> > I translated the texts at some point - and saved them in a table so that I don't have to do that again and again ;-)
> 
> Ok, that's good. And how about other text that need to be translated? If you use same XLF file that can be downloaded from your blog, it might not work as expected.

But why?
I install the  update, then I define my application languages, seed, upload and apply my XLF from the last app, check the strings, and publish afterwards.

This has worked every time so far...

**Comment by scl-4711** [comment]
Now everything works - I deletet the browser cache, and the application cache via "Manage Service -> Application Cache -> Purge all cached pages for the specified application.

I hate errors that I cannot explain - thanks for your help.

**Comment by jariolaine** [comment]
> But why?

I mean cases where region source has changed. Example that shortcut BLOG_POWERED_BY was in region source and I replaced it static HTML.

Great you did get it working. 
I need keep closer look translations and mention more detail changes. Sorry about this.

**Comment by scl-4711** [comment]
No problem - for me, translating with APEX is a chapter in itself and not always understandable...
