### ISSUE TITLE
Application Language Derived From always English

### ISSUE THREAD

**Issue by scl-4711** [jariolaine/apex-blog#3]
Could you please set "Broswer (use browser language preference)" as default?
![Browser-Language](https://user-images.githubusercontent.com/12970066/162573900-73ea74ae-5368-46bb-a4bf-28fa0a86fb9a.png)

Why? I translated your app (to german) and don't want to change it everytime you update your app ;-)

**Comment by jariolaine** [comment]
Sure, I will do that. Thanks for reporting this!

**Comment by jariolaine** [comment]
Change implemented on latest release
