### ISSUE TITLE
Are you interested in the (german) translated app?

### ISSUE THREAD

**Issue by scl-4711** [jariolaine/apex-blog#4]
Hi.
if you're interested in the (german) translated app,  I can upload it ...
Happy Easter

**Comment by jariolaine** [comment]
Hi,
Thanks. That's great! But think I can't maintain those translations.
How about if you share it in your own Github page?

Happy Easter

**Comment by scl-4711** [comment]
I shared it at [my blog](https://asc.web-republic.de/ords/r/sc/blog/post?p2_post_id=20220416115826704550) :-)

**Comment by jariolaine** [comment]
Thank you
