### ISSUE TITLE
APEX 21.2 -  Font APEX Icon "fa-rss-square" is empty (?)

### ISSUE THREAD

**Issue by scl-4711** [jariolaine/apex-blog#5]
Hi Jari,
I can't believe it - the "fa-rss-square" has an empty icon in APEX 21.2...
I searched over a hour because I thougt it has to do with translation...

I use "fa-feed" now...

![fa-rss-square](https://user-images.githubusercontent.com/12970066/163675394-b41496ce-bed2-4c40-b049-dd57037d04c3.png)

**Comment by jariolaine** [comment]
I'm using APEX 21.2.5 and instance IMAGE_PRIFIX points to CDN https://static.oracle.com/cdn/apex/21.2.4/
There is that icon. You can check from my blog that it's displayed correctly.
https://cloud.jaris.fi/ords/r/jaris/blog/home

What is your exact APEX version you use?

**Comment by jariolaine** [comment]
When check [your blog](https://asc.web-republic.de/ords/r/sc/blog/home) and using browser developer tools, I can see that you also have icon fa-rss-square.
Could your problem be e.g. browser cache? Try clear cache and see if it helps.

**Comment by scl-4711** [comment]
I'm at 21.2.5 too - Free Autonomous Transaction Database @OracleCloud...

Very interesting, if I look at my blog with dev tools I see fa-feed 😉 

If I will find the error I'll post it here ...

**Comment by jariolaine** [comment]
Yes, now icon in right hand column is that fa-feed as you have changed it. But when I did inspect element using browser developer tools and changes class back to fa-rss-square, I can see correct icon. 
From that I think you should have that icon.
