### ISSUE TITLE
Enhancement - CKEditor5

### ISSUE THREAD

**Issue by scl-4711** [jariolaine/apex-blog#6]
Hi Jari,
first of all, Merry Christmas and a Happy New Year 2023.

I have an enhancement request:

Could you please integrate the folllowing javascript snippet in the "_JavaScript code for item initialization_", f.e. 
P12_BODY_HTML in APP 401.

```
function ( options ) {
  // link - activate "Open in a new tab" switch
  options.editorOptions.link = {
    decorators: {
      openInNewTab: {
        mode: "manual",
        label: "Open in a new tab",
        attributes: {
          target: "_blank",
          rel: "noopener noreferrer"
        }
      }
    }
  };
  return options ;
}
```

Thank you in advance.

By the way - there are many other [features](https://ckeditor.com/docs/ckeditor5/latest/features/) for CKEditor5

**Comment by jariolaine** [comment]
Implemented to branch APEX_22.2 and will be available on next release.
